version: '3.8'

services:
  # HTTP transport for remote access
  cdata-sync-mcp-http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdata-sync-mcp-http
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - MCP_TRANSPORT_MODE=http
      - MCP_HTTP_PORT=3000
      - SSE_PORT=3001
      - DISABLE_SSE=false
      - CDATA_BASE_URL=${CDATA_BASE_URL:-http://host.docker.internal:8181/api.rsc}
      - CDATA_AUTH_TOKEN=${CDATA_AUTH_TOKEN}
      - CDATA_USERNAME=${CDATA_USERNAME}
      - CDATA_PASSWORD=${CDATA_PASSWORD}
      - DEBUG_HTTP=${DEBUG_HTTP:-false}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/mcp/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cdata-network

  # Both transports for development
  cdata-sync-mcp-both:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdata-sync-mcp-both
    restart: unless-stopped
    ports:
      - "3002:3000"  # HTTP on different port to avoid conflicts
      - "3003:3001"  # SSE on different port
    environment:
      - MCP_TRANSPORT_MODE=both
      - MCP_HTTP_PORT=3000
      - SSE_PORT=3001
      - DISABLE_SSE=false
      - CDATA_BASE_URL=${CDATA_BASE_URL:-http://host.docker.internal:8181/api.rsc}
      - CDATA_AUTH_TOKEN=${CDATA_AUTH_TOKEN}
      - CDATA_USERNAME=${CDATA_USERNAME}
      - CDATA_PASSWORD=${CDATA_PASSWORD}
      - DEBUG_HTTP=${DEBUG_HTTP:-false}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/mcp/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cdata-network

  # Development environment with hot reload
  cdata-sync-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cdata-sync-mcp-dev
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
      - ./dist:/app/dist
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    ports:
      - "3004:3000"
      - "3005:3001"
    environment:
      - MCP_TRANSPORT_MODE=${MCP_TRANSPORT_MODE:-both}
      - MCP_HTTP_PORT=3000
      - SSE_PORT=3001
      - DISABLE_SSE=false
      - CDATA_BASE_URL=${CDATA_BASE_URL:-http://host.docker.internal:8181/api.rsc}
      - CDATA_AUTH_TOKEN=${CDATA_AUTH_TOKEN}
      - CDATA_USERNAME=${CDATA_USERNAME}
      - CDATA_PASSWORD=${CDATA_PASSWORD}
      - DEBUG_HTTP=${DEBUG_HTTP:-true}
      - NODE_ENV=development
    networks:
      - cdata-network
    profiles:
      - dev

networks:
  cdata-network:
    driver: bridge