# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app

# Copy package manifests and TypeScript config
COPY package.json package-lock.json tsconfig.json ./

# Copy source code
COPY src ./src

# Install dependencies without running lifecycle scripts, then build
RUN npm ci --ignore-scripts \
    && npm run build

# Remove dev dependencies to shrink image
RUN npm prune --production

ENV NODE_ENV=production

# Default command: start the MCP server in stdio mode
CMD ["node", "dist/index.js"]
