apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdata-sync-mcp-server
  namespace: cdata-sync
  labels:
    app: cdata-sync-mcp-server
    component: mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdata-sync-mcp-server
  template:
    metadata:
      labels:
        app: cdata-sync-mcp-server
        component: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: cdata-sync-mcp-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: sse
          containerPort: 3001
          protocol: TCP
        env:
        - name: MCP_TRANSPORT_MODE
          value: "http"
        - name: MCP_HTTP_PORT
          value: "3000"
        - name: SSE_PORT
          value: "3001"
        - name: DISABLE_SSE
          value: "false"
        - name: NODE_ENV
          value: "production"
        - name: CDATA_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: cdata-sync-config
              key: base-url
        - name: CDATA_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: cdata-sync-secrets
              key: auth-token
              optional: true
        - name: CDATA_USERNAME
          valueFrom:
            secretKeyRef:
              name: cdata-sync-secrets
              key: username
              optional: true
        - name: CDATA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cdata-sync-secrets
              key: password
              optional: true
        - name: DEBUG_HTTP
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /mcp/v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /mcp/v1/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL