apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdata-sync

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: cdata-sync-mcp-server
    newName: your-registry.com/cdata-sync-mcp-server  # Update with your registry
    newTag: latest

configMapGenerator:
  - name: cdata-sync-config
    behavior: merge
    literals:
      - log-level=info

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cdata-sync-mcp-server
    spec:
      template:
        spec:
          containers:
          - name: mcp-server
            env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cdata-sync-config
                  key: log-level