apiVersion: v1
kind: Secret
metadata:
  name: cdata-sync-secrets
  namespace: cdata-sync
  labels:
    app: cdata-sync-mcp-server
type: Opaque
stringData:
  # Choose either token authentication or basic auth
  # Option 1: API Token (recommended)
  auth-token: "your-cdata-sync-api-token-here"
  
  # Option 2: Basic Auth
  # username: "your-username"
  # password: "your-password"